### ISSUE TITLE
[feat]:Main 온보딩 API 구현

### ISSUE THREAD

**Issue by spacewalk00** [Kusitms-29th-MeetUp-H/Back#34]
### 📝 Description

- 유저 정보 저장 API
- 학교 이메일 인증 API
- 국가 조회 API

---

### 📝 Todo

- [x] : 유저 정보 저장 API
- [x] : 이메일 인증 API 
- [x] : 학교이메일 인증 API
- [x] : 국가 조회 API
