### ISSUE TITLE
[feat]:Main 싱크 상세보기 api 구현

### ISSUE THREAD

**Issue by qogustj** [Kusitms-29th-MeetUp-H/Back#45]
### 📝 Description

- 일회성/내친소 api
- 지속성 api

---

### 📝 Todo

- [ ] : 일회성/내친소 -싱크 상세내용
- [ ] : 일회성/내친소 -표
- [ ] : 일회성/내친소 -같은 요일, 장소 추천
- [ ] : 지속성 -싱크 상세내용
- [ ] : 지속성 -표
- [ ] : 지속성 -리뷰
- [ ] : 지속성 -같은 요일, 장소 추천
