### ISSUE TITLE
[feat]:Main 푸쉬 알림 구현

### ISSUE THREAD

**Issue by spacewalk00** [Kusitms-29th-MeetUp-H/Back#70]
### 📝 Description

기획 우선순위대로

- 푸쉬 알림 
  - **CHAT**, **NOTICE** 
  - SYNC_REMINDER
  - **COMMENT**
  - **REVIEW**

- 사용자 알림 저장
  - **CHAT**, **NOTICE** 
  - **SYNC_REMINDER**
  - **COMMENT**
  - **REVIEW** 

- 채널 Id 포함해서 안드로이드 단에서 알림설정 처리  

---

### 📝 Todo

- [x] : 채팅 푸쉬 알림과 저장 -> 테스트 아직
- [x] : 채팅방 개설 공지 푸쉬 알림과 저장 -> 채팅 개설 중 참여하는 인원에게 알람보내는 거 추가예정 
- [x] : 싱크 리마인드 저장
- [x] : 커뮤니티 알림과 저장
- [ ] : 리뷰 알림과 저장
- [x] : 채널 Id 포함해서 안드로이드 단에서 알림설정 처리
